[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "xfoil"
version = "0.0.4"
description = "Python wrapper for XFOIL"
requires-python = ">=3.6"